In [1]:
import pandas as pd

In [2]:
vine_df = pd.read_csv('vine_table.csv')
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RED72VWWCOS7S,1.0,2.0,8.0,N,Y
1,RZHWQ208LTEPV,5.0,0.0,0.0,N,Y
2,R37LBC3XAVLYOO,5.0,4.0,5.0,N,Y
3,R3L7XJMA0MVJWC,5.0,0.0,0.0,N,Y
4,R2I2GHSI7T1UBN,1.0,5.0,6.0,N,Y
...,...,...,...,...,...,...
2557283,R3MV8JFJJJ3WU0,2.0,12.0,12.0,N,N
2557284,RGL89WE5DFU75,5.0,19.0,24.0,N,N
2557285,R203ZDOKV987E5,3.0,231.0,236.0,N,N
2557286,R8GD7D9HK6S2W,5.0,17.0,29.0,N,N
2557287,R2QCF5NWYPK06U,5.0,86.0,106.0,N,N